spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
cloud:
  aws:
    s3:
      bucket: everywhere-s3-bucket.bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
